[tool.poetry]
name = "cheatsheets"
version = "0.1.0"
description = "Just my cheatsheets of different stuff like Python, git, pandas, Linux etc"
authors = ["RandyRomero <a.ya.miheev@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pandas = "^0.25.3"
xlrd = "^1.2.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
